# Generated by Django 4.2.11 on 2024-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('passenger_capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'airplane',
                'verbose_name_plural': 'airplanes',
            },
        ),
    ]
